### ISSUE TITLE
Implement BiDAF+Self attention

### ISSUE THREAD

**Issue by AkariAsai** [AkariAsai/BiDAF_PyTorch#1]
Implement BiDAF + self attention model. 

## Background 
- [Simple and Effective Multi-Paragraph Reading Comprehension](https://arxiv.org/pdf/1710.10723.pdf) shows the improved BiDAF model with self attention layer or some recent techniques of Neural Reading Comprehension achieves significantly higher performance of F1 and EM.
- Preliminary experiment shows that the [Tensorflow implementation](https://github.com/allenai/document-qa) performs better especially with a noisy test dataset. 

## TODO
- [ ]  Detail observation (Which layers are added? How to calculate self-attention layer?) of BiDAF and BIDAF + self attention.
- [ ]  Add another model file to define BiDAF + Self attention.
- [ ]  Compare the performance.

## Deadline
- Need to implement this by April 20th, which is an acceptance notification of ACL 2018.
